# Generated by Django 3.2.6 on 2021-08-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id_answers', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('points', models.SmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
