# Generated by Django 3.2.6 on 2021-08-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='id_answers',
            new_name='id_answer',
        ),
    ]
